#!/bin/sh
_hostname=$(hostname)
_version=$(cut -d"'" -f2 < /usr/local/lib/python3.11/dist-packages/bananagotchi/_version.py)
echo
echo "(☉_☉ ) $_hostname"
echo
echo "    Hi! I'm a bananagotchi $_version, please take good care of me!"
echo "    Here are some basic things you need to know to raise me properly!"
echo
echo "    If you want to change my configuration, use /etc/bananagotchi/config.toml"
echo "    All plugin config files are located in /etc/bananagotchi/conf.d/"
echo "    Read the readme if you want to use gdrivesync plugin!!"
echo
echo "    All the configuration options can be found on /etc/bananagotchi/default.toml,"
echo "    but don't change this file because I will recreate it every time I'm restarted!"
echo
echo "    I use oPwnGrid as my main API, you can check stats at https://opwngrid.xyz"
echo
echo "    I'm managed by systemd. Here are some basic commands."
echo
echo "    If you want to know what I'm doing, you can check my logs with the command"
echo "    - pwnlog"
echo "    - sudo bananagotchi --version, to check the current version"
echo "    - sudo bananagotchi --donate, to see how you can donate to this project"
echo "    - sudo bananagotchi --check-update, to see if there is a new version available"
echo
echo "    If you want to know if I'm running, you can use"
echo "    sudo systemctl status bananagotchi"
echo
echo "    You can restart me using"
echo "    pwnkill"
echo
echo "    You can learn more about me at https://bananagotchi.org/"
